name: fasum_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  #sdk: ^3.5.4
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_app_check: ^0.2.2
  firebase_database: ^10.5.7
  firebase_core: ^2.32.0
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  flutter_image_compress: ^2.4.0
  google_generative_ai: ^0.4.7
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true